import { Dimensions, StyleSheet } from 'react-native';
import { DOT_SIZE, DotInactive, SkipGray, SubtitleGray, Teal, TealDark, White } from './slides';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  splashContainer: { flex: 1, backgroundColor: White },
  splashSafeArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  splashMascotWrapper: {
    marginBottom: 16,
    shadowColor: TealDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  splashMascotImage: { width: width * 0.64, height: width * 0.64 },
  splashLogo: { width: width * 0.58, height: width * 0.17, marginBottom: 8 },
  splashTagline: {
    fontSize: 16.5,
    color: Teal,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 24,
    letterSpacing: 0.2,
  },
  container: { flex: 1, backgroundColor: White },
  flatListWrapper: { flex: 1 },
  skipButton: {
    position: 'absolute',
    top: 14,
    right: 20,
    zIndex: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(241, 245, 249, 0.8)',
  },
  skipButtonText: { fontSize: 14, color: SkipGray, fontWeight: '600' },
  slide: { width, flex: 1 },
  slideInner: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 68,
  },
  slideTitle: {
    fontSize: 25,
    fontWeight: '800',
    color: '#0F172A',
    textAlign: 'center',
    lineHeight: 34,
    marginBottom: 10,
    letterSpacing: -0.3,
  },
  slideSubtitle: {
    fontSize: 15,
    color: SubtitleGray,
    textAlign: 'center',
    lineHeight: 23,
    paddingHorizontal: 8,
  },
  imageWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  footer: { alignItems: 'center', paddingBottom: 28 },
  dotContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    marginBottom: 20,
  },
  dot: { height: DOT_SIZE, width: DOT_SIZE, borderRadius: DOT_SIZE / 2 },
  dotInactive: { backgroundColor: DotInactive },
  buttonSlot: {
    width: '100%',
    height: 132,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 24,
  },
  buttonGroup: { width: '100%' },
  primaryButton: {
    width: '100%',
    backgroundColor: Teal,
    paddingVertical: 16,
    borderRadius: 9999,
    alignItems: 'center',
    shadowColor: TealDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 6,
  },
  primaryButtonLabel: { fontSize: 16.5, fontWeight: '700', color: White, letterSpacing: 0.3 },
  secondaryButton: {
    width: '100%',
    backgroundColor: White,
    paddingVertical: 15,
    borderRadius: 9999,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Teal,
    marginTop: 12,
  },
  secondaryButtonLabel: { fontSize: 16, fontWeight: '700', color: Teal },
});
