spring.datasource.url=jdbc:postgresql://localhost:5432/carenest_dev
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

spring.jpa.show-sql=true

carenest.seed.enabled=true

logging.level.com.carenest=DEBUG
logging.level.org.flywaydb=DEBUG