import { StyleSheet } from 'react-native';
import { Colors } from '../../../../core/theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  scroll: { padding: 20 },
  avatarMascot: { width: '100%', height: '100%', borderRadius: 999 },
  brandFooter: { alignItems: 'center', marginTop: 24 },
  brandFooterImage: { width: 140, height: 44, opacity: 0.85 },
  avatarWrap: { alignItems: 'center' },
  avatarStack: { position: 'relative' },
  avatarCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: `${Colors.secondary}1A`,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarCameraBadge: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: Colors.surface,
  },
  avatarName: { fontSize: 22, fontWeight: '700', color: Colors.textPrimary },
  avatarPhone: { color: Colors.textSecondary, fontSize: 14 },
  roleBadge: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: `${Colors.secondary}1A`,
  },
  roleBadgeText: { color: Colors.secondary, fontSize: 13, fontWeight: '600' },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 18,
    padding: 18,
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  cardHeaderTitle: { fontSize: 16, fontWeight: '700', color: Colors.textPrimary },
  divider: { height: 1, backgroundColor: Colors.divider, marginVertical: 12 },
  elderlyRow: { flexDirection: 'row', alignItems: 'center' },
  elderlyAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: `${Colors.primary}1A`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  elderlyInfo: { flex: 1, marginLeft: 12 },
  elderlyName: { fontWeight: '600', fontSize: 15, color: Colors.textPrimary },
  elderlySubtitleRow: { flexDirection: 'row', marginTop: 2 },
  elderlySubtitle: { color: Colors.textSecondary, fontSize: 12 },
  statusDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: Colors.success },
  addFamilyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: `${Colors.primary}33`,
    padding: 18,
  },
  addFamilyIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: `${Colors.primary}14`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addFamilyText: { flex: 1, marginLeft: 14 },
  addFamilyTitle: { color: Colors.primary, fontSize: 15, fontWeight: '600' },
  addFamilySubtitle: { color: Colors.textSecondary, fontSize: 12, marginTop: 2 },
  scanQRCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: `${Colors.secondary}33`,
    padding: 18,
  },
  scanQRIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: `${Colors.secondary}14`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanQRTitle: { color: Colors.secondary, fontSize: 15, fontWeight: '600' },
  settingsCard: {
    backgroundColor: Colors.surface,
    borderRadius: 18,
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    overflow: 'hidden',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  settingIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingLabel: {
    flex: 1,
    marginLeft: 14,
    fontSize: 15,
    fontWeight: '500',
    color: Colors.textPrimary,
  },
  settingDivider: { height: 1, backgroundColor: Colors.divider, marginLeft: 72 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    padding: 32,
  },
  dialog: { backgroundColor: Colors.surface, borderRadius: 16, padding: 20 },
  dialogTitle: { fontSize: 17, fontWeight: '700', color: Colors.textPrimary },
  dialogBody: { color: Colors.textSecondary, fontSize: 13 },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(173, 181, 189, 0.4)',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 48,
  },
  inputIcon: { marginRight: 8 },
  input: { flex: 1, fontSize: 15, color: Colors.textPrimary, height: '100%' },
  dialogActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
  dialogCancelBtn: { paddingHorizontal: 12, paddingVertical: 10 },
  dialogCancelText: { color: Colors.textSecondary, fontSize: 14, fontWeight: '600' },
  dialogSendBtn: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
  },
  dialogSendBtnDisabled: { opacity: 0.6 },
  dialogSendText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
});
