import { StyleSheet } from 'react-native';
import { Colors } from '../../../../core/theme/colors';
import { Shadows } from '../../../../core/theme/spacing';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  scroll: { padding: 20 },
  avatarMascot: { width: '100%', height: '100%' },
  brandFooter: { alignItems: 'center', marginTop: 28, marginBottom: 8 },
  brandFooterImage: { width: 140, height: 44, opacity: 0.8 },
  avatarWrap: { alignItems: 'center' },
  avatarStack: {
    width: 108,
    height: 108,
    ...Shadows.lg,
  },
  avatarCircle: {
    width: 108,
    height: 108,
    borderRadius: 54,
    backgroundColor: '#E6F7F5',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  avatarCameraBadge: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  avatarName: { fontSize: 22, fontWeight: '900', color: '#0F172A', letterSpacing: -0.3 },
  phonePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 4,
  },
  avatarPhone: { color: '#475569', fontSize: 13.5, fontWeight: '600' },
  roleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#ECFDF5',
  },
  roleBadgeText: { color: '#059669', fontSize: 13, fontWeight: '700' },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    ...Shadows.md,
  },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#E6F7F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardHeaderTitle: { fontSize: 16.5, fontWeight: '800', color: '#0F172A' },
  cardHeaderSub: { fontSize: 12.5, color: '#64748B', marginTop: 1, fontWeight: '500' },
  divider: { height: 1, backgroundColor: '#F1F5F9', marginVertical: 14 },
  elderlyRow: { flexDirection: 'row', alignItems: 'center' },
  elderlyAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#E6F7F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  elderlyInfo: { flex: 1, marginLeft: 14 },
  elderlyName: { fontWeight: '800', fontSize: 16.5, color: '#0F172A' },
  elderlySubtitleRow: { flexDirection: 'row', marginTop: 3 },
  elderlySubtitle: { color: '#64748B', fontSize: 13, fontWeight: '500' },
  statusDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#10B981' },
  addFamilyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: '#BAE6FD',
    padding: 18,
    ...Shadows.sm,
  },
  addFamilyIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: '#E0F2FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addFamilyText: { flex: 1, marginLeft: 14 },
  addFamilyTitle: { color: '#0369A1', fontSize: 15.5, fontWeight: '800' },
  addFamilySubtitle: { color: '#64748B', fontSize: 12.5, marginTop: 2, lineHeight: 17 },
  scanQRCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: '#A7F3D0',
    padding: 18,
    ...Shadows.sm,
  },
  scanQRIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: '#D1FAE5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanQRTitle: { color: '#047857', fontSize: 15.5, fontWeight: '800' },
  settingsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    ...Shadows.md,
    overflow: 'hidden',
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  settingsIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsLabel: {
    marginLeft: 14,
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
  },
  settingsDivider: { height: 1, backgroundColor: '#F1F5F9', marginLeft: 72 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'center',
    padding: 24,
  },
  dialog: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    ...Shadows.lg,
  },
  dialogTitle: { fontSize: 18, fontWeight: '800', color: '#0F172A' },
  dialogBody: { color: '#64748B', fontSize: 13.5, lineHeight: 20, marginTop: 6 },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 52,
    backgroundColor: '#F8FAFC',
    marginTop: 14,
  },
  inputIcon: { marginRight: 10 },
  input: { flex: 1, fontSize: 15, color: '#0F172A', height: '100%' },
  dialogActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 18 },
  dialogCancelBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12 },
  dialogCancelText: { color: '#64748B', fontSize: 14, fontWeight: '700' },
  dialogSendBtn: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
  },
  dialogSendBtnDisabled: { opacity: 0.6 },
  dialogSendText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
});
