import { StyleSheet } from 'react-native';
import { Colors } from '../../../../core/theme/colors';
import { Shadows } from '../../../../core/theme/spacing';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  scroll: { padding: 20 },
  avatarMascot: { width: '100%', height: '100%' },
  brandFooter: { alignItems: 'center', marginTop: 28, marginBottom: 8 },
  brandFooterImage: { width: 140, height: 44, opacity: 0.8 },
  avatarWrap: { alignItems: 'center' },
  avatarStack: {
    width: 104,
    height: 104,
    ...Shadows.lg,
  },
  avatarCircle: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: Colors.secondaryLighter,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: Colors.surface,
  },
  avatarCameraBadge: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: Colors.surface,
  },
  avatarName: { fontSize: 22, fontWeight: '800', color: Colors.textPrimary },
  avatarPhone: { color: Colors.textSecondary, fontSize: 14, fontWeight: '500' },
  roleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: Colors.primaryLighter,
  },
  roleBadgeText: { color: Colors.primary, fontSize: 13, fontWeight: '700' },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Shadows.md,
  },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: Colors.primaryLighter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardHeaderTitle: { fontSize: 16, fontWeight: '800', color: Colors.textPrimary },
  divider: { height: 1, backgroundColor: Colors.divider, marginVertical: 14 },
  elderlyRow: { flexDirection: 'row', alignItems: 'center' },
  elderlyAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.primaryLighter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  elderlyInfo: { flex: 1, marginLeft: 14 },
  elderlyName: { fontWeight: '700', fontSize: 16, color: Colors.textPrimary },
  elderlySubtitleRow: { flexDirection: 'row', marginTop: 2 },
  elderlySubtitle: { color: Colors.textSecondary, fontSize: 12.5, fontWeight: '500' },
  statusDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: Colors.success },
  addFamilyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#BAE6FD',
    padding: 18,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  addFamilyIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: Colors.primaryLighter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addFamilyText: { flex: 1, marginLeft: 14 },
  addFamilyTitle: { color: Colors.primaryDark, fontSize: 15, fontWeight: '800' },
  addFamilySubtitle: { color: Colors.textSecondary, fontSize: 12, marginTop: 2, lineHeight: 17 },
  scanQRCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#A7F3D0',
    padding: 18,
    shadowColor: Colors.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  scanQRIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: Colors.secondaryLighter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanQRTitle: { color: Colors.secondaryDark, fontSize: 15, fontWeight: '800' },
  settingsCard: {
    backgroundColor: Colors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Shadows.md,
    overflow: 'hidden',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  settingIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingLabel: {
    flex: 1,
    marginLeft: 14,
    fontSize: 15,
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  settingDivider: { height: 1, backgroundColor: Colors.divider, marginLeft: 72 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'center',
    padding: 24,
  },
  dialog: {
    backgroundColor: Colors.surface,
    borderRadius: 24,
    padding: 24,
    ...Shadows.lg,
  },
  dialogTitle: { fontSize: 18, fontWeight: '800', color: Colors.textPrimary },
  dialogBody: { color: Colors.textSecondary, fontSize: 13.5, lineHeight: 20 },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 52,
    backgroundColor: '#F8FAFC',
  },
  inputIcon: { marginRight: 10 },
  input: { flex: 1, fontSize: 15, color: Colors.textPrimary, height: '100%' },
  dialogActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  dialogCancelBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12 },
  dialogCancelText: { color: Colors.textSecondary, fontSize: 14, fontWeight: '700' },
  dialogSendBtn: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
  },
  dialogSendBtnDisabled: { opacity: 0.6 },
  dialogSendText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
});
